---
Name: dynamicblocksconfig
---
SiteTree:
  extensions:
    - DynamicBlocksSiteTreeDataExtension
ContentBlock:
  extensions:
    - DynamicContentBlockDataExtension
SlideshowBlock:
  extensions:
    - FlexSlider
SlideImage:
  extensions:
    - DynamicBlocksSlideImageDataExtension
Link:
  templates:
    button: 'Display link as a button'