---
Name: dynamicblocksconfig
---
SilverStripe\CMS\ModelSiteTree:
  extensions:
    - Dynamic\DynamicBlocks\ORM\DynamicBlocksSiteTreeDataExtension
SheaDawson\Blocks\Model\ContentBlock:
  extensions:
    - Dynamic\DynamicBlocks\ORM\DynamicContentBlockDataExtension
Dynamic\DynamicBlocks\SlideshowBlock:
  extensions:
    - Dynamic\FlexSlider\ORM\FlexSlider
Dynamic\FlexSlider\Model\SlideImage:
  extensions:
    - Dynamic\DynamicBlocks\ORM\DynamicBlocksSlideImageDataExtension
Link:
  templates:
    button: 'Display link as a button'
Dynamic\DynamicBlocks\Model\AccordionPanel:
  extensions:
    - SilverStripe\Versioned\Versioned('Stage','Live')
Dynamic\DynamicBlocks\CustomerServiceBlock:
  extensions:
    - Dynamic\Locator\AddressDataExtension
Dynamic\DynamicBlocks\Model\PageSectionObject:
  extensions:
    - SilverStripe\Versioned\Versioned('Stage','Live')
Dynamic\DynamicBlocks\Model\PhotoGalleryBlockImage:
  extensions:
    - SilverStripe\Versioned\Versioned('Stage','Live')
Dynamic\DynamicBlocks\Model\PromoObject:
  extensions:
    - SilverStripe\Versioned\Versioned('Stage','Live')