---
Name: dynamicblocksconfig
---
SiteTree:
  extensions:
    - DynamicBlocksSiteTreeDataExtension
Block:
  extensions:
    - DynamicBlocksBlockDataExtension
ContentBlock:
  extensions:
    - DynamicContentBlockDataExtension
SlideshowBlock:
  extensions:
    - FlexSlider
SlideImage:
  extensions:
    - DynamicBlocksSlideImageDataExtension
Link:
  templates:
    button: 'Display link as a button'
    buttonghost: 'Display link as a ghost button'
CustomerServiceBlock:
  extensions:
    - Addressable
    - Geocodable